server {
    listen 80;
    
    # Nginx가 파일들을 찾을 기본 경로
    root /usr/share/nginx/html;
    index index.html;

    location / {
        # 요청된 URI가 파일이나 디렉토리로 존재하지 않으면 index.html로 라우팅
        try_files $uri $uri/ /index.html;
    }
}
